default:
    pattern:  /
    defaults: { _controller: SystemTrackingBundle:Default:home }

system_tracking_rest:
    prefix: /api
    type: rest
    resource: "@SystemTrackingBundle/Resources/config/routing_rest.yml"

default_locale_routing:
    resource: "routing_default.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|pl