security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        api:
            pattern: ^/api(?!\/v1\/devices\.json)
            stateless: true
            simple_preauth:
                authenticator: device_apikey_authenticator
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path:     system_tracking_homepage
                login_path:     fos_user_security_login 
                check_path:     fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: system_tracking_homepage
            anonymous:    true

    access_control:
        - { path: ^/[^/]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN