system_tracking_homepage:
    pattern:  /
    defaults: { _controller: SystemTrackingBundle:Default:index }
    
# devices
system_tracking_device:
    pattern:  /devices
    defaults: { _controller: SystemTrackingBundle:Device:index }
    
system_tracking_device_edit:
    pattern:  /devices/edit/{id}
    defaults: { _controller: SystemTrackingBundle:Device:edit }
    
system_tracking_device_delete:
    pattern:  /devices/delete/{id}
    defaults: { _controller: SystemTrackingBundle:Device:delete }

# objects
system_tracking_object:
    pattern:  /objects
    defaults: { _controller: SystemTrackingBundle:Object:index }
    
system_tracking_object_new:
    pattern:  /objects/new
    defaults: { _controller: SystemTrackingBundle:Object:new }
    
system_tracking_object_delete:
    pattern:  /objects/delete/{id}
    defaults: { _controller: SystemTrackingBundle:Object:delete }
    
system_tracking_object_edit:
    pattern:  /objects/edit/{id}
    defaults: { _controller: SystemTrackingBundle:Object:edit }
    
# trips
system_tracking_trip:
    pattern:  /trips/{id}
    defaults: { _controller: SystemTrackingBundle:Trip:index }
    
system_tracking_trip_view:
    pattern:  /trips/view/{id}
    defaults: { _controller: SystemTrackingBundle:Trip:view }
    
system_tracking_trip_track:
    pattern:  /track
    defaults: { _controller: SystemTrackingBundle:Object:track }
    