parameters:
#    system_tracking.example.class: System\TrackingBundle\Example

services:
    system.twig.api.state:
        class: System\TrackingBundle\DependencyInjection\TrackingState
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]