parameters:
    system_tracking.device.handler.class: System\TrackingBundle\Handler\DeviceHandler
    system_tracking.object.handler.class: System\TrackingBundle\Handler\ObjectHandler

services:
    system.twig.api.state:
        class: System\TrackingBundle\DependencyInjection\TrackingState
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
    system.device.notificator:
        class: System\TrackingBundle\DependencyInjection\DeviceNotificator
        arguments: ["@doctrine.orm.entity_manager", "@rms_push_notifications", "@jms_serializer"]
    system.device.notificationmanager:
        class: System\TrackingBundle\DependencyInjection\DeviceNotificationsManager
        arguments: ["@doctrine.orm.entity_manager", "@system.device.notificator"]
    system_tracking.device.handler:
        class: %system_tracking.device.handler.class%
        arguments: ["@doctrine.orm.entity_manager", "System\TrackingBundle\Entity\Device", "@form.factory", "@fos_user.user_manager", "@security.encoder_factory"]
    system_tracking.object.handler:
        class: %system_tracking.object.handler.class%
        arguments: ["@doctrine.orm.entity_manager", "System\TrackingBundle\Entity\Object"]